language: c

sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ondrej/autotools -y # automake 1.15
  - sudo add-apt-repository ppa:cz.nic-labs/knot-dns -y # pkg-config 0.29.2
  - sudo apt-get update
  - sudo apt-get install -y autoconf automake-1.15 pkg-config m4 libsndfile-dev libfftw3-dev libasound2-dev

env:
  - AUTOGEN=true SHARED=OFF SHARED=ON BUILD_TYPE=Debug
  - AUTOGEN=false SHARED=OFF SHARED=ON BUILD_TYPE=Release
  - AUTOGEN=false SHARED=ON SHARED=ON BUILD_TYPE=Debug
  - AUTOGEN=false SHARED=ON SHARED=ON BUILD_TYPE=Release

script:
  - if $AUTOGEN; then ./autogen.sh && ./configure && make distcheck; fi
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=$SHARED -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cat config.h
  - make
  - make test
