image:
- Visual Studio 2017

environment:
  matrix:
    - generator: "Visual Studio 15 2017"
      shared: "OFF"
    - generator: "Visual Studio 15 2017"
      shared: "ON"
    - generator: "MSYS Makefiles"
      shared: "OFF"
    - generator: "MSYS Makefiles"
      shared: "ON"

matrix:
  fast_finish: true

build_script:
  - export PATH=C:\\MinGW\\msys\\1.0\\bin;%PATH%
  - mkdir build
  - cd build
  - cmake -G "%generator%" -DBUILD_SHARED_LIBS=%shared% ..
  - cat config.h
  - cmake --build .
  - ctest -C "Debug"
