image:
- Visual Studio 2017

environment:
  matrix:
    # - generator: "Visual Studio 15 2017"
    #   shared: "OFF"
    # - generator: "Visual Studio 15 2017"
    #   shared: "ON"
    - generator: "MSYS Makefiles"
      shared: "OFF"
    - generator: "MSYS Makefiles"
      shared: "ON"

matrix:
  fast_finish: true

build_script:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - bash -lc "pacman -S --needed --noconfirm mingw-w64-x86_64-fftw mingw-w64-x86_64-libsndfile"
  - mkdir build
  - cd build
  - cmake -G "%generator%" -DBUILD_SHARED_LIBS=%shared% ..
  - cat config.h
  - cmake --build .
  - ctest -C "Debug"
